# Generated by Django 5.2.7 on 2025-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
